[project]
name = "cppcg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tree-sitter>=0.25",
    "tree-sitter-cpp>=0.23"
]

[tool.setuptools]
package-dir = {"cppcg" = "cppcg"}

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-timeout"
]

[tool.pytest.ini_options]
testpaths = ["test"]
